[package]
name = "slip"
version = "0.1.0"
authors = ["Kaoru Chisen <cordx56@cordx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm11-0"] }
clap = "2"
